# Floor Table Cleaning

In [58]:
import pandas as pd
import json
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

In [59]:
floor_info = pd.read_csv("bs_harvest_floors.csv")

In [60]:
floor_info.head()

,uuid,harvest_id,stargate_floor_id,stargate_property_id,data,_fivetran_synced,_fivetran_deleted,floor_id,property_id
0,d25b0d13-64f0-44f8-a2e6-7469279c9fed,27fdf1f1-84ef-4418-a08a-b0cbff9f7e27,NaN,NaN,"{""name"":""1ST FLOOR"",""uuid"":""e49c10a5-2f67-4b01...",2018-05-13 01:07:50.052,NaN,6e4ed9f8-949a-11e7-9d13-0642b0acf810,a95ce973-948b-11e7-9d13-0642b0acf810
1,40e475dc-f664-4723-afaa-f8bbe3fa9326,b5d1aa7b-aae7-4f78-9e8c-014c21373b31,4646.0,3521.0,"{""gsf"":null,""usf"":27531,""name"":""29TH FLOOR"",""u...",2018-05-13 01:07:49.573,NaN,dea128fa-0e12-11e6-9312-063c4950d72f,f7b141a0-8e11-0132-226b-1efb49eb59b4
2,03a8d852-cfca-4777-bb8b-1becefb90e03,f3bd0cc7-b868-4275-b384-15b2bc5240e2,4842.0,4837.0,"{""name"":""1ST FLOOR"",""uuid"":""650a0288-059c-4a9a...",2018-05-13 01:07:49.376,NaN,dea13e3f-0e12-11e6-9312-063c4950d72f,5e8d8f30-aef7-0132-a603-3ecb6520abc5
3,940f770e-ef10-4a02-9e9f-62d0781a1b98,3256f5ac-ed6f-43c6-8346-c7ac11bbc58b,8044.0,7426.0,"{""gsf"":null,""usf"":29229,""name"":""4TH FLOOR"",""uu...",2018-05-13 01:07:49.853,NaN,b98d53e0-239c-11e6-9312-063c4950d72f,55c2ae8d-1e01-11e6-9312-063c4950d72f
4,f229ad66-95cf-4f4f-af6a-fbea0744c7a7,0b1abac3-acce-4d7f-b951-f27604797ecb,11072.0,NaN,"{""name"":""9TH FLOOR"",""uuid"":""dd5423c7-a5b6-4bdd...",2018-05-13 01:07:50.143,NaN,d7416af3-6785-11e7-a99c-063c4950d72f,27b184e0-45d9-11e7-a99c-063c4950d72f

In [61]:
# abstract infomation from 'data' for each floor

n_row = floor_info.shape[0]

col_name = list(json.loads(floor_info.data.iloc[0]).keys())
stats_col = col_name.copy()
floor_data_stats  = pd.DataFrame(columns = stats_col)

for i in range(n_row):
    f_info = json.loads(floor_info.data.iloc[i])

    if 'stage' in f_info.keys():
        f_info['stage'] = f_info['stage']['name']
    if 'outline' in f_info.keys():
        f_info['outline'] = str(f_info['outline'])
        
    df = pd.DataFrame(f_info, index = [i])
    floor_data_stats = floor_data_stats.append(df)

In [62]:
floor_data_stats.rename(columns={'uuid':'uuid_from_data'}, inplace=True)

In [63]:
floor_data_stats

,FIVETRAN_ERROR,average_office_desk_count,desk_count,elevation,floor_id,floor_to_bottom_of_beam,floor_to_floor,floorplan_image_extents,geometric_level,gsf,name,nysf,outline,rsf,soft_seating_count,stage,stargate_floor_id,usf,usf_per_desk,uuid_from_data
0,NaN,NaN,214,12,6e4ed9f8-949a-11e7-9d13-0642b0acf810,0,0,NaN,1,0,1ST FLOOR,NaN,"[['(201.643957631986, 67.0003857598667, 12)', ...",NaN,None,Open,NaN,11300.6,NaN,e49c10a5-2f67-4b01-ad19-ede3da84c26e-0071368b
1,NaN,NaN,470,336.125,NaN,None,None,NaN,28,None,29TH FLOOR,NaN,NaN,NaN,None,Open,4646.0,27531,NaN,3163c5f6-ceae-40a9-a1e6-17ca672d37f8-005445ea
2,NaN,NaN,32,13.9167,NaN,None,None,None,1,None,1ST FLOOR,NaN,NaN,NaN,None,Open,4842.0,4628.06,NaN,650a0288-059c-4a9a-ba4e-52a71cfb3bcb-00671d80
3,NaN,NaN,639,36,NaN,None,None,NaN,NaN,None,4TH FLOOR,NaN,NaN,NaN,None,Test Fit,8044.0,29229,NaN,f62afe97-1e64-4854-b51f-7fed19dbc8df-00551d13
4,NaN,NaN,383,104.659,d7416af3-6785-11e7-a99c-063c4950d72f,0,0,NaN,8,0,9TH FLOOR,NaN,None,NaN,None,Pre-Design,11072.0,18860,NaN,dd5423c7-a5b6-4bdd-b963-af6c6f90864d-007a0593
5,NaN,NaN,165,0,0fc23c2f-4a9f-11e6-9312-063c4950d72f,0,0,NaN,0,0,1ST FLOOR,NaN,"[['(140.000066954217, 61.0000048453708, 0)', '...",NaN,None,Design,8197.0,8540,NaN,43cedad1-4e33-43d6-8256-5940f2e660e5-007cbe62
6,NaN,NaN,477,72.125,NaN,None,None,None,6,None,6TH FLOOR,NaN,NaN,NaN,None,Open,5330.0,25537.8,NaN,b08abcf6-8b4d-48fc-ac93-13ced1280304-006871b1
7,NaN,NaN,269,127.953,e2c3c2a7-1536-11e7-9312-063c4950d72f,0,0,NaN,0,0,10TH FLOOR,NaN,"[['(326.461608629316, 149.114173219022, 127.95...",NaN,None,Design,9840.0,12908,NaN,9adf79d8-21cf-46b2-8d32-3278f9e1e370-007a0cde
8,NaN,NaN,296,62.2117,7b56eb81-1468-11e7-9312-063c4950d72f,0,0,NaN,5,0,FIFTH FLOOR,NaN,"[['(46.9115482965168, 259.316634388799, 62.211...",NaN,None,Construction,9823.0,15562,NaN,518b089c-fdbb-408f-b75f-21dcf3f3995c-0072e515
9,NaN,NaN,288,30.1667,NaN,None,None,NaN,NaN,None,4TH FLOOR,NaN,NaN,NaN,None,Open,5815.0,13515,NaN,8460745f-e8ab-4f98-a5b3-0ced8e4e30a9-00069602
10,NaN,NaN,192,31.8419,NaN,None,None,NaN,3,None,3RD FLOOR,NaN,NaN,NaN,None,Open,4942.0,12297,NaN,6c4c4903-7c15-4fa2-90e7-5beb1b9d4b30-00050fcf
11,NaN,NaN,158,44.1312,NaN,None,None,NaN,NaN,0,Level 4,NaN,NaN,NaN,None,Open,7378.0,8251.54,NaN,6e2412ef-8fc4-4a02-ba36-e76ee1fa99ad-000008e6
12,NaN,NaN,269,36.125,e9f491db-46e5-11e7-a99c-063c4950d72f,0,0,NaN,3,0,3RD FLOOR,NaN,"[['(182.166733620884, 92.0937548453711, 36.125...",NaN,None,Pre-Construction,10354.0,14950.5,NaN,0711d48e-c6f7-4f05-9e42-17de6bd97ea3-00792d73
13,NaN,NaN,482,23.7381,236bbbe2-6d6d-11e7-a99c-063c4950d72f,0,0,NaN,2,0,3RD FLOOR,NaN,"[['(117.291476993161, 221.159763257466, 23.738...",NaN,None,Pre-Design,11155.0,23546.4,NaN,984be60d-7cfd-4b41-ad63-bdac0c25a427-00792f3a
14,NaN,NaN,284,0.125,NaN,None,None,None,0,None,1st Floor,NaN,NaN,NaN,None,Open,5048.0,17310,NaN,da1707ce-f413-4eb0-9ea7-3d806a2f6cf7-005436f9
15,NaN,NaN,298,45,NaN,None,None,None,4,None,4TH FLOOR,NaN,NaN,NaN,None,Construction,7839.0,15470,NaN,5a264eba-a05b-4fa3-a2ad-fa47b426c472-006856de
16,NaN,NaN,307,252,5fe045e5-14af-11e7-9312-063c4950d72f,None,None,NaN,0,None,22ND FLOOR,NaN,"[['(133.857476419, 142.139288107, 252.00000000...",NaN,None,Construction,9837.0,14482.1,NaN,8b4f73d2-5470-410a-bc97-a45258247d02-0075d5a6
17,NaN,NaN,397,24.125,NaN,None,None,NaN,2,None,3RD FLOOR,NaN,NaN,NaN,None,Open,4741.0,19517.8,NaN,eef21462-ccee-4d4b-9770-e1f0e9abf7e2-00540d9a
18,NaN,NaN,191,100.5,NaN,None,None,NaN,7,None,8TH FLOOR,NaN,"[['(-33.948975718, -17.281250000, 100.50000000...",NaN,None,Open,7188.0,9556.83,NaN,c8a4ef9f-6f83-443d-ae5c-28902d07cdb0-00687ebf
19,NaN,NaN,230,369.351,d6f72e46-0221-11e7-9312-063c4950d72f,0,0,NaN,35,0,35TH FLOOR,NaN,"[['(29.0152441286869, 46.5059076489584, 369.35...",NaN,None,Open,9535.0,11513.1,NaN,e68ce81c-e1e0-49aa-a1a0-01ce8a94e84d-00764f72
20,NaN,NaN,177,45.4583,NaN,None,None,NaN,4,None,5TH FLOOR,NaN,NaN,NaN,None,Open,6879.0,8494,NaN,dfaf7171-c496-4eee-a1be-6ec7acc400e0-0068dd14
21,NaN,NaN,325,48.1667,dea441c8-0e12-11e6-9312-063c4950d72f,None,None,NaN,4,None,5TH FLOOR,NaN,"[['(211.320701477, 114.770956119, 48.166666667...",NaN,None,Open,6584.0,16118,NaN,59cc10e6-1557-466b-8840-eaab9b912288-00687526
22,NaN,NaN,204,154.441,dea7780b-0e12-11e6-9312-063c4950d72f,0,0,NaN,14,0,14TH FLOOR,NaN,"[['(-40.9224336727044, 16.2855818370848, 154.4...",NaN,None,Pre-Construction,7539.0,10195.5,NaN,54e66325-74aa-4dc1-b66f-7e417b45a8de-0072ed09
23,NaN,NaN,125,93.5046,NaN,None,None,NaN,8,None,9TH FLOOR,NaN,"[['(58.364339360, 169.284493773, 93.504639801)...",NaN,None,Design,8624.0,8009,NaN,e5cdc0ea-410d-46dd-8a3e-e91b30dee1d1-006882cd
24,NaN,NaN,211,48,72dc40db-949a-11e7-9d13-0642b0acf810,0,0,NaN,4,0,4TH FLOOR,NaN,"[['(201.676835721963, 66.9031113651882, 48)', ...",NaN,None,Construction,NaN,11278.1,NaN,e49c10a5-2f67-4b01-ad19-ede3da84c26e-00713c13
25,NaN,NaN,480,48.125,NaN,None,None,NaN,4,None,5TH FLOOR,NaN,NaN,NaN,None,Open,5008.0,33463,NaN,b8246afa-100b-4572-af2a-4149ac121e12-0054339e
26,NaN,NaN,459,24,NaN,None,None,NaN,0,None,Level 2,NaN,NaN,NaN,None,Open,5342.0,22690,NaN,6e2412ef-8fc4-4a02-ba36-e76ee1fa99ad-000008e5
27,NaN,NaN,0,0.125,NaN,None,None,NaN,0,0,1st Floor,NaN,NaN,NaN,None,Open,4723.0,1649,NaN,248d7b09-98f3-4653-9974-be45f7923087-005436f9
28,NaN,NaN,205,40.4692,NaN,None,None,NaN,0,None,Level 3,NaN,NaN,NaN,None,Construction,7886.0,10023,NaN,6e2412ef-8fc4-4a02-ba36-e76ee1fa99ad-000008e6
29,NaN,NaN,148,93.4649,735df880-0283-11e7-9312-063c4950d72f,0,0,NaN,7,0,8TH FLOOR,NaN,"[['(89.2274495102877, 138.097191903336, 93.464...",NaN,None,Design,9551.0,10429.7,NaN,d22e2bcd-8011-4750-88b7-2be7f0381acc-00765300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40246,NaN,NaN,92,139.333,5d42759e-9109-11e8-9d13-0642b0acf810,0,0,NaN,11,0,12TH FLOOR,NaN,"[['(69.5000000000015, 69.5000000000003, 139.33...",NaN,None,Pre-Construction,NaN,0,NaN,37ff2ac5-7b55-4dfd-ad43-f5d88e01a4bc-00a64bc0
40247,NaN,NaN,282,26.6404,18db72aa-2c6e-11e8-9d13-0642b0acf810,0,0,NaN,0,0,2ND FLOOR,NaN,"[['(45.0740432707608, 138.587748424472, 26.640...",NaN,None,Design,NaN,14508.2,NaN,d8920ad3-644d-43ff-b0b1-9efc5f82e120-0084414e
40248,NaN,NaN,390,163.386,29a8f29e-88a9-11e8-9d13-0642b0acf810,0,0,NaN,12,0,12TH FLOOR,NaN,None,NaN,None,Design,NaN,19910,NaN,4f1f184e-3ed4-4814-a431-8262fbc5ae9f-0084d56f
40249,NaN,NaN,202,73.9439,d0231e5c-4f38-11e9-b223-0626947414d8,0,0,NaN,5,0,5TH FLOOR,NaN,"[['(47.3966534966107, 121.227034128654, 73.943...",NaN,None,Pre-Design,NaN,10274.5,NaN,9dd03b07-6101-4485-8cb3-1a11e054cadb-009aec79
40250,NaN,NaN,629,36,6ee19570-8a6d-11e8-9d13-0642b0acf810,0,0,NaN,0,0,Level 302,NaN,None,NaN,None,Design,NaN,0,NaN,2dc75c64-6ce9-484d-aed1-d38232a42597-00c62d4c
40251,NaN,NaN,0,36,71ab8886-77cd-11e8-9d13-0642b0acf810,0,0,NaN,3,0,3RD FLOOR,NaN,"[['(-1.2696900186499, 109.140175217721, 36)', ...",NaN,None,Testfit,NaN,22015,NaN,36eaaf49-2ec1-4352-b734-a4bc9007a76e-0084434c
40252,NaN,NaN,318,35.9518,256b8ce4-71bd-11e9-b223-0626947414d8,0,0,NaN,3,0,3RD FLOOR,NaN,"[['(198.456483576429, 10.7068525198313, 35.951...",NaN,None,Pre-Design,NaN,15753.5,NaN,140bf8a7-46c6-42a1-88ab-0fac4924eaf7-009356cf
40253,NaN,NaN,200,24.5751,db4c9504-45b8-11e9-b223-0626947414d8,0,0,NaN,3,0,3RD FLOOR,NaN,"[['(63.30497275412, 82.5951190142109, 24.57513...",NaN,None,Pre-Design,NaN,10117.7,NaN,74d1bdd6-b8f0-4878-ad5f-8c7706cb78d6-00932469
40254,NaN,NaN,67,4.26509,8e5473fc-cd3a-11e8-b223-0626947414d8,0,0,NaN,1,0,1ST FLOOR,NaN,"[['(38.0406178619165, 80.3208684171813, 4.2650...",NaN,None,Design,NaN,6021,NaN,2058145a-0ecc-464b-af26-d0e9c2c3cfdc-00a14235
40255,NaN,NaN,436,0,10b96151-7bab-11e9-b223-0626947414d8,0,0,NaN,0,0,0 GROUND FLOOR,NaN,"[['(90.9417173570355, 130.547783919537, 0)', '...",NaN,None,Testfit,NaN,23172,NaN,c5809094-d4d9-460c-b3f2-a1b4627d3b4f-00885cbb
40256,NaN,NaN,59,177.333,5d6267d8-9109-11e8-9d13-0642b0acf810,0,0,NaN,14,0,15TH FLOOR,NaN,"[['(69.2203383801442, 69.2037505026182, 177.33...",NaN,None,Pre-Construction,NaN,0,NaN,37ff2ac5-7b55-4dfd-ad43-f5d88e01a4bc-00a6508e
40257,NaN,NaN,252,130.407,dea43716-0e12-11e6-9312-063c4950d72f,0,0,NaN,8,0,9TH FLOOR,NaN,None,NaN,None,Design,6562.0,14038,NaN,415a45c1-4a5c-4fd8-8223-7026ef5b5a44-00845a56
40258,NaN,NaN,353,62.0046,55137c92-e299-11e8-b223-0626947414d8,0,0,NaN,6,0,6TH FLOOR,NaN,"[['(129.150297211588, 126.989990178972, 62.004...",NaN,None,Testfit,NaN,21320,NaN,0e36bfb0-93ba-4d11-9c2d-f3ec4ab5cac5-00a2a261
40259,NaN,NaN,0,48,1e826860-61de-11e9-b223-0626947414d8,0,0,NaN,4,0,6TH FLOOR,NaN,"[['(-0.695562381607997, -0.494683465286472, 48...",NaN,None,Testfit,NaN,5619,NaN,4fef38ec-ded5-400c-bed4-6ad27b656f97-00886708
40260,NaN,NaN,72,42.6509,da40079e-f701-11e8-b223-0626947414d8,0,0,NaN,4,0,4TH FLOOR,NaN,"[['(-50.3783262133106, 44.8190469529671, 42.65...",NaN,None,Design,NaN,5518.1,NaN,368c30f4-e13b-4bff-978f-0fcd17553bca-0093630e
40261,NaN,NaN,0,120,4d1e8cfb-664c-11e9-b223-0626947414d8,0,0,NaN,10,0,11TH FLOOR,NaN,"[['(-27.0317545403741, 56.4019251445034, 120)'...",NaN,None,Testfit,NaN,4230.02,NaN,3dc2751b-fae6-450e-b7ae-3f965c206c80-00a5fd8c
40262,NaN,NaN,276,0,fe4f5f5d-6972-11e8-9d13-0642b0acf810,0,0,NaN,0,0,0 GROUND FLOOR,NaN,"[['(-128.38535236376, 16.3163747711176, 0)', '...",NaN,None,Pre-Design,NaN,19868.2,NaN,34b1da7c-beaa-4370-bf8b-04e6aead9ab3-009abd61
40263,NaN,NaN,405,24,46417f05-bfd4-11e8-b223-0626947414d8,0,0,NaN,2,0,2ND FLOOR,NaN,"[['(-2.0078740157465, 56.1351706036747, 24)', ...",NaN,None,Design,NaN,14960,NaN,f79b6ea5-0e14-4905-8003-1a5d41597e3b-00885f61
40264,NaN,NaN,380,275.262,46aef079-af3f-11e8-9d13-0642b0acf810,0,0,NaN,19,0,19TH FLOOR,NaN,"[['(4.95031342216409, 142.836637067282, 275.26...",NaN,None,Design,NaN,19178.2,NaN,18a4dd5d-d1bf-4a91-b57f-f351033b4097-009990eb
40265,NaN,NaN,328,64.9872,eb73206f-d09b-11e8-b223-0626947414d8,0,0,NaN,6,0,7TH FLOOR,NaN,"[['(-98.0932687319879, -9.51924576083245, 64.9...",NaN,None,Design,NaN,21271,NaN,5bc94bc2-e5c5-4544-bd9b-62c398a4c1e4-00932df1
40266,NaN,NaN,139,79.2214,c669a643-7de7-11e8-9d13-0642b0acf810,0,0,NaN,6,0,6TH FLOOR,NaN,"[['(60.7035661937463, 56.9838342696489, 79.221...",NaN,None,Construction,NaN,7131.33,NaN,4b07ee03-851f-4b05-9a9d-bdfbff2773a8-008841ed
40267,NaN,NaN,95,101.333,5d215998-9109-11e8-9d13-0642b0acf810,0,0,NaN,8,0,9TH FLOOR,NaN,"[['(69.2650211973929, 69.252612281763, 101.333...",NaN,None,Pre-Construction,NaN,0,NaN,37ff2ac5-7b55-4dfd-ad43-f5d88e01a4bc-00a646f2
40268,NaN,NaN,192,144.482,89e029e9-baa6-11e8-9d13-0642b0acf810,0,0,NaN,10,0,10TH FLOOR,NaN,"[['(-50.9815012014877, 35.3491421149461, 144.4...",NaN,None,Pre-Construction,NaN,9650.95,NaN,3e58fc81-8aa8-45e9-9350-4994b5e5e3d2-0092cd67
40269,NaN,NaN,64,0,b744271d-2dbc-11e9-b223-0626947414d8,0,0,NaN,0,0,GROUND FLOOR,NaN,"[['(164.465509637866, -90.5183717938303, 0)', ...",NaN,None,Design,NaN,10393,NaN,d73d92a5-b3d1-41fc-a744-892882e1b463-00885cd7
40270,NaN,NaN,186,84,4061f730-05a9-11e9-b223-0626947414d8,0,0,NaN,7,0,7TH FLOOR,NaN,"[['(52.2017487493852, -0.0699343041552762, 84)...",NaN,None,Testfit,NaN,9972,NaN,ccc292b9-4f71-4026-962c-d7a110bed72c-00845ec7
40271,NaN,NaN,179,43.5708,731655b2-ed4d-11e6-9312-063c4950d72f,0,0,NaN,3,0,4TH FLOOR,NaN,"[['(112.107985564829, 76.7933991952077, 43.570...",NaN,None,Design,9311.0,0,NaN,dfcc0bbe-6bd8-4e1b-a64d-b1fcc73512c2-00c14cab
40272,NaN,NaN,138,6.74871,3e82b906-16f7-11e8-9d13-0642b0acf810,0,0,NaN,1,0,1 MEZZANINE 1,NaN,"[['(-9.87532808398941, -20.7020997375326, 6.74...",NaN,None,Construction,NaN,8300.84,NaN,faf8617b-4ca3-424a-a255-59665b2c8fe5-008838e1
40273,NaN,NaN,222,88,ed8dca88-f8bb-11e8-b223-0626947414d8,0,0,NaN,7,0,8TH FLOOR,NaN,"[['(-0.0821786652853179, -0.562576225637187, 8...",NaN,None,Design,NaN,0,NaN,2ed954c5-f4ac-43ec-85ac-99f4689649ff-00a8e42c
40274,NaN,NaN,250,15.6419,a55814de-7de7-11e8-9d13-0642b0acf810,0,0,NaN,1,0,1ST FLOOR,NaN,"[['(-80.7051593454124, 163.727993128093, 15.64...",NaN,None,Construction,NaN,14175.4,NaN,4b07ee03-851f-4b05-9a9d-bdfbff2773a8-0088369e
40275,NaN,NaN,385,0,001393f1-65df-11e8-9d13-0642b0acf810,0,0,NaN,4,0,4TH FLOOR,NaN,"[['(156.579204690133, 129.017254220237, 0)', '...",NaN,None,Open,NaN,0,NaN,527e7622-b8f8-455f-b462-abc4980964f6-008e0f87

In [64]:
# Keep features from original table:
#  ---- 'uuid': unique id of floor plan; 
#  ---- 'property_id': unique id of each building (a property may contain multiple floor plans since multiple-level ); 
#  ---- '_fivetran_synced': created date at system
floor_basic = floor_info[['uuid','property_id', 'harvest_id', 'floor_id', 'stargate_floor_id', 'stargate_property_id', '_fivetran_synced']]

# delete 'uuid' in floor_data_stats (?) not clear
# floor_data_stats = floor_data_stats.drop(['uuid'], axis=1)

# combine two tables to get whole information of floor 
if floor_data_stats.shape[0] == floor_basic.shape[0]:
    floor_df = pd.concat([floor_basic, floor_data_stats], axis=1, join_axes=[floor_basic.index])
else:
    floor_df = pd.concat([floor_basic, floor_data_stats], axis=1, join_axes=[floor_basic.index])
    print('warning! You may check your table dimension')
print('shape of floor_data_stats', floor_data_stats.shape)
print('shape of floor_basic', floor_basic.shape) 
print('shape of floor_df(merged)', floor_df.shape)

shape of floor_data_stats (40276, 20)
shape of floor_basic (40276, 7)
shape of floor_df(merged) (40276, 27)

In [65]:
# let's look at floor_df and save it to local
print(floor_df.columns)
floor_df.head()

Index(['uuid', 'property_id', 'harvest_id', 'floor_id', 'stargate_floor_id',
       'stargate_property_id', '_fivetran_synced', 'FIVETRAN_ERROR',
       'average_office_desk_count', 'desk_count', 'elevation', 'floor_id',
       'floor_to_bottom_of_beam', 'floor_to_floor', 'floorplan_image_extents',
       'geometric_level', 'gsf', 'name', 'nysf', 'outline', 'rsf',
       'soft_seating_count', 'stage', 'stargate_floor_id', 'usf',
       'usf_per_desk', 'uuid_from_data'],
      dtype='object')

,uuid,property_id,harvest_id,floor_id,stargate_floor_id,stargate_property_id,_fivetran_synced,FIVETRAN_ERROR,average_office_desk_count,desk_count,...,name,nysf,outline,rsf,soft_seating_count,stage,stargate_floor_id,usf,usf_per_desk,uuid_from_data
0,d25b0d13-64f0-44f8-a2e6-7469279c9fed,a95ce973-948b-11e7-9d13-0642b0acf810,27fdf1f1-84ef-4418-a08a-b0cbff9f7e27,6e4ed9f8-949a-11e7-9d13-0642b0acf810,NaN,NaN,2018-05-13 01:07:50.052,NaN,NaN,214,...,1ST FLOOR,NaN,"[['(201.643957631986, 67.0003857598667, 12)', ...",NaN,None,Open,NaN,11300.6,NaN,e49c10a5-2f67-4b01-ad19-ede3da84c26e-0071368b
1,40e475dc-f664-4723-afaa-f8bbe3fa9326,f7b141a0-8e11-0132-226b-1efb49eb59b4,b5d1aa7b-aae7-4f78-9e8c-014c21373b31,dea128fa-0e12-11e6-9312-063c4950d72f,4646.0,3521.0,2018-05-13 01:07:49.573,NaN,NaN,470,...,29TH FLOOR,NaN,NaN,NaN,None,Open,4646.0,27531,NaN,3163c5f6-ceae-40a9-a1e6-17ca672d37f8-005445ea
2,03a8d852-cfca-4777-bb8b-1becefb90e03,5e8d8f30-aef7-0132-a603-3ecb6520abc5,f3bd0cc7-b868-4275-b384-15b2bc5240e2,dea13e3f-0e12-11e6-9312-063c4950d72f,4842.0,4837.0,2018-05-13 01:07:49.376,NaN,NaN,32,...,1ST FLOOR,NaN,NaN,NaN,None,Open,4842.0,4628.06,NaN,650a0288-059c-4a9a-ba4e-52a71cfb3bcb-00671d80
3,940f770e-ef10-4a02-9e9f-62d0781a1b98,55c2ae8d-1e01-11e6-9312-063c4950d72f,3256f5ac-ed6f-43c6-8346-c7ac11bbc58b,b98d53e0-239c-11e6-9312-063c4950d72f,8044.0,7426.0,2018-05-13 01:07:49.853,NaN,NaN,639,...,4TH FLOOR,NaN,NaN,NaN,None,Test Fit,8044.0,29229,NaN,f62afe97-1e64-4854-b51f-7fed19dbc8df-00551d13
4,f229ad66-95cf-4f4f-af6a-fbea0744c7a7,27b184e0-45d9-11e7-a99c-063c4950d72f,0b1abac3-acce-4d7f-b951-f27604797ecb,d7416af3-6785-11e7-a99c-063c4950d72f,11072.0,NaN,2018-05-13 01:07:50.143,NaN,NaN,383,...,9TH FLOOR,NaN,None,NaN,None,Pre-Design,11072.0,18860,NaN,dd5423c7-a5b6-4bdd-b963-af6c6f90864d-007a0593

In [66]:
floor_df.to_csv('floor_CLEANED.csv',index=False)